### ISSUE TITLE
Partituras trocadas

### ISSUE THREAD

**Issue by edsonma** [brunopedroso/vqf#24]
As partes da Bananeira (Gm) em  bb e eb estão trocadas. Inclusive o título!

Percebi no ultimo ensaio com o Rodrigo!

**Comment by rodrigoesborges** [comment]
Edson 

Consertei ontem, aproveita e já veja no meu fork se deu certo
https://rodrigoesborges.github.io/vqf/repertorio.html

**Comment by rodrigoesborges** [comment]
@brunopedroso acho que já dá para fechar isto
